stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: maven:3.5.2-jdk-8
      shellScript: mvn clean install
- name: 发布
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: renren-fast
      registry: 127.0.0.1:34988
timeout: 60
notification: {}
